### ISSUE TITLE
[BUG] NPC window not appearing ?

### ISSUE THREAD

**Issue by Steelskinz** [averrin/alpha-hud#3]
**Module Version:** v0.1.3

**Describe the bug**
NPC info does not appears.
**To Reproduce**
1. Drop an NPC
2. Click on it.
3. Enjoy black square.

**Expected behavior**
Well ... To see infos like the description of the module ?
**Screenshots**
Player :
![image](https://user-images.githubusercontent.com/93941729/181411798-511a0f0a-43ea-4ace-9cf1-43e9e1bbaa50.png)
NPC :
![image](https://user-images.githubusercontent.com/93941729/181411739-d323b092-2d6a-4f88-bed7-ad358f4cb093.png)

**Browser:**
 - Vivaldi

**Foundry Version:** 0.9.... Something.

**Game System:** D&D5e

**Additional context**
I tried with only this one activated, will do the same.

**Comment by averrin** [comment]
Could you please provide what kind of error is present in console? Open Developer Tools (ctrl-shift-i) and look for red text in console. Because it's working for me right now. It means the module encountered some error, probably during fetching data from your NPC. I should know what happens for fixing =)

**Comment by Steelskinz** [comment]
I always forgot the console, here you go 
![image](https://user-images.githubusercontent.com/93941729/181574910-c7e7b779-607d-46b1-821b-efe059c97d90.png)
I just realized that I'm missing some feature too even with the player interface, I might reinstall the module maybe.
Edit : Reinstalling the module is not working. I should say that i'm right now hosting on Oracle Cloud is it an issue for fetching data ?

**Comment by averrin** [comment]
Thank you very much, will fix it in an hour.

**Comment by averrin** [comment]
I hope https://github.com/averrin/alpha-hud/releases/tag/0.1.4 fixes this issue.

**Comment by averrin** [comment]
Please reopen the issue, if it didn't fix.
